jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build core and unit test with gradle
      run: cd core && ./gradlew build
    - continue-on-error: true
      name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ChkBugReport
        path: core/build/distributions/ChkBugReport.tar
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
